# sudo docker-compose build --no-cache
# sudo docker-compose up -d
version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
       - '80:80'   #production

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    container_name: docker-node-mongo
    restart: unless-stopped
    build: .
    # ports:
    #   - '5000:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  