version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: unless-stopped
    build: .
    # ports:
    #   - '5000:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      # - '8080:80' #develop
      - '8080:80'   #production

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf